#/EPol/construct/magFile polarimeter_magnet.dat.5GeV
#/EPol/input/name /volatile/halla/moller12gev/ciprian/tmp/compton/e5GeV_g532nm_Pz98Px22.cr

# /EPol/construct/magFile polarimeter_magnet.dat.10GeV
# /EPol/input/name /volatile/halla/moller12gev/ciprian/tmp/compton/e10GeV_g532nm_Pz91Px42.cr

/EPol/construct/magFile ip6V2_polarimeter_magnet.dat
/EPol/input/name /volatile/halla/moller12gev/ciprian/tmp/compton/e18GeV_g532nm_Pz71Px71.cr

/EPol/construct/quadHoles false
/EPol/construct/quadPartTransparency true

#detectors and components
/EPol/input/vertexPosX 1.4199963 m
/EPol/input/vertexPosY 0 cm
/EPol/input/vertexPosZ 94.532737 m
/EPol/input/vertexRotY 0.018681542 rad

## trasnverse size comes from photon beam
/EPol/input/vertexSmearXY 0.01 cm

## longitudinal size comes from electron beam
# 5,10 GeV
#/EPol/input/vertexSmearZ 0.7 cm
## 18 GeV
/EPol/input/vertexSmearZ 0.9 cm

# Initialize kernel
/run/initialize
/compton/output/name /volatile/halla/moller12gev/ciprian/tmp/compton/o_e18Pz71Px71_VtxSmearXY0p1Z9mm_5e6.root
/run/beamOn 5000000

