/EPol/construct/magFile ip6V3_polarimeter_magnet.dat
#/EPol/input/name /volatile/halla/moller12gev/ciprian/tmp/compton/e18GeV_g532nm_Pz59Pxm81_1e6.cr
/EPol/input/name /volatile/halla/moller12gev/ciprian/tmp/compton/e5GeV_g532nm_Pz97Pxm26_1e6.cr

/EPol/construct/beamEnergy 5 GeV
/EPol/construct/quadHoles false
/EPol/construct/quadPartTransparency true

#before Q6 detector
/EPol/input/vertexPosX 0.4278 m
/EPol/input/vertexPosY 0 cm
/EPol/input/vertexPosZ 71.530 m
/EPol/input/vertexRotY -0.01547 rad

## trasnverse size comes from photon beam
/EPol/input/vertexSmearXY 0.0 cm

## longitudinal size comes from electron beam
# 5,10 GeV
#/EPol/input/vertexSmearZ 0.7 cm
## 18 GeV
/EPol/input/vertexSmearZ 0. cm

# Initialize kernel
/run/initialize
/compton/output/name /volatile/halla/moller12gev/ciprian/tmp/compton/o_e5Pz97Pxm26_ip6V3p1_VtxSmearXY0Z0_1e6.root
/run/beamOn 1000000

